---

- name: Install Apache and PHP on Ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Apache and PHP on CentOS
  dnf: 
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start and enable Apache on CentOS
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"
